Author:
    type: object
    config:
        description: "This is a author"
        fields:
            id:
                type: "Int!"
                description: "The id of the author."
                # to deprecate a field, only set the deprecation reason
                #deprecationReason: "A terrible reason"
            name:
                type: "String!"
                description: "The name of the author."
            bio:
                type: "String!"
                description: "the bio of the author."